import { useState } from "react";
import { motion, AnimatePresence } from "motion/react";
import { 
  FileText, 
  Search, 
  Download, 
  Eye, 
  ChevronRight, 
  FileCode, 
  FileJson, 
  Image as ImageIcon,
  FolderOpen,
  X,
  Copy,
  Check
} from "lucide-react";
import { FileAsset } from "../types";

interface FilesViewProps {
  files: FileAsset[];
}

export default function FilesView({ files }: FilesViewProps) {
  const [fileSearch, setFileSearch] = useState("");
  const [selectedFile, setSelectedFile] = useState<FileAsset | null>(null);
  const [copied, setCopied] = useState(false);

  const filteredFiles = files.filter(f => 
    f.name.toLowerCase().includes(fileSearch.toLowerCase()) ||
    f.projectName.toLowerCase().includes(fileSearch.toLowerCase())
  );

  const handleCopy = (content: string) => {
    navigator.clipboard.writeText(content);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = (file: FileAsset) => {
    const element = document.createElement("a");
    const blob = new Blob([file.content], { type: "text/plain" });
    element.href = URL.createObjectURL(blob);
    element.download = file.name;
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
  };

  // Highlighting key syntax in code/text files
  const styleCodeLines = (code: string) => {
    if (!code) return "";
    return code
      .split("\n")
      .map((line, idx) => {
        // Simple highlighting for common coding terms
        const escaped = line
          .replace(/&/g, "&amp;")
          .replace(/</g, "&lt;")
          .replace(/>/g, "&gt;")
          .replace(/(const|let|var|function|import|export|from|return|class|extends|interface|type)/g, '<span class="text-white font-bold">$1</span>')
          .replace(/(true|false|null|undefined)/g, '<span class="text-[#A1A1AA] font-semibold">$1</span>')
          .replace(/("[^"]*"|'[^']*')/g, '<span class="text-[#A1A1AA]">$1</span>')
          .replace(/(\/\/.*$)/g, '<span class="text-[#71717A] font-light font-mono">$1</span>');

        return `<div class="table-row"><span class="table-cell select-none pr-4 text-right text-[#71717A] font-mono text-[10px] w-8">${idx + 1}</span><span class="table-cell font-mono text-xs text-[#FAFAFA] whitespace-pre-wrap">${escaped}</span></div>`;
      })
      .join("");
  };

  return (
    <div className="space-y-6" id="files-view">
      {/* Search and header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h2 className="text-2xl font-bold tracking-tight text-white font-sans">Delivered Workspace Files</h2>
          <p className="text-xs text-[#A1A1AA] font-light mt-1">Access actual production-ready code modules, wireframes design specs, and promotional campaign documents generated by the AI employees.</p>
        </div>

        <div className="relative w-full sm:w-64">
          <Search className="absolute left-3 top-2.5 w-4 h-4 text-[#71717A]" />
          <input 
            type="text" 
            placeholder="Search generated assets..." 
            value={fileSearch}
            onChange={(e) => setFileSearch(e.target.value)}
            className="w-full bg-[#18181B] border border-[#27272A] focus:border-neutral-500 focus:outline-none pl-9 pr-4 py-2 rounded-lg text-xs text-white font-sans transition-colors"
          />
        </div>
      </div>

      {/* Grid Explorer */}
      {filteredFiles.length === 0 ? (
        <div className="text-center py-24 border border-dashed border-[#27272A] rounded-xl space-y-3 p-4">
          <FolderOpen className="w-10 h-10 text-[#71717A] mx-auto" />
          <h4 className="text-sm font-bold text-[#A1A1AA]">No generated files yet</h4>
          <p className="text-xs text-[#71717A] max-w-sm mx-auto leading-relaxed"> Standby until employees finalize active startup tasks. Elena will deliver assets directly to this folder.</p>
        </div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
          {filteredFiles.map((file) => (
            <div 
              key={file.id}
              className="border border-[#27272A] bg-[#18181B] p-4 rounded-xl hover:border-neutral-500 transition-all flex flex-col justify-between"
            >
              <div>
                <div className="flex items-center space-x-3 mb-3">
                  <div className="w-9 h-9 bg-[#09090B] border border-[#27272A] flex items-center justify-center text-white rounded-lg">
                    {file.type === "code" ? (
                      <FileCode className="w-5 h-5" />
                    ) : file.type === "design" ? (
                      <FileJson className="w-5 h-5" />
                    ) : (
                      <FileText className="w-5 h-5" />
                    )}
                  </div>
                  <div className="truncate">
                    <h4 className="font-bold text-white text-xs truncate">{file.name}</h4>
                    <span className="text-[9px] text-[#71717A] font-mono uppercase">{file.type} // {file.size}</span>
                  </div>
                </div>

                <div className="bg-[#09090B] border border-[#27272A] p-3 rounded-lg text-[10px] text-[#A1A1AA] font-mono line-clamp-3 leading-relaxed mb-4">
                  {file.content}
                </div>
              </div>

              <div className="flex items-center justify-between border-t border-[#27272A] pt-3 mt-1">
                <span className="text-[9px] text-[#71717A] font-mono truncate max-w-[50%]">{file.projectName}</span>
                <div className="flex items-center space-x-1">
                  <button 
                    onClick={() => setSelectedFile(file)}
                    className="p-1.5 hover:bg-[#27272A] text-[#A1A1AA] hover:text-white rounded-lg transition-colors"
                    title="Inspect file"
                  >
                    <Eye className="w-4 h-4" />
                  </button>
                  <button 
                    onClick={() => handleDownload(file)}
                    className="p-1.5 hover:bg-[#27272A] text-[#A1A1AA] hover:text-white rounded-lg transition-colors"
                    title="Download file"
                  >
                    <Download className="w-4 h-4" />
                  </button>
                </div>
              </div>
            </div>
          ))}
        </div>
      )}

      {/* Code Editor Inspector Overlay Modal */}
      <AnimatePresence>
        {selectedFile && (
          <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/80 backdrop-blur-md">
            <motion.div 
              initial={{ opacity: 0, scale: 0.95 }}
              animate={{ opacity: 1, scale: 1 }}
              exit={{ opacity: 0, scale: 0.95 }}
              className="border border-[#27272A] bg-[#18181B] w-full max-w-4xl h-[80vh] rounded-2xl flex flex-col justify-between overflow-hidden shadow-2xl"
            >
              {/* Header Editor style */}
              <div className="flex items-center justify-between bg-[#18181B] border-b border-[#27272A] p-4">
                <div className="flex items-center space-x-2">
                  <div className="flex space-x-1.5 mr-2">
                    <span className="w-3 h-3 rounded-full bg-[#27272A]" />
                    <span className="w-3 h-3 rounded-full bg-[#27272A]" />
                    <span className="w-3 h-3 rounded-full bg-[#27272A]" />
                  </div>
                  <span className="text-xs text-[#FAFAFA] font-mono font-bold pr-2">{selectedFile.name}</span>
                  <span className="text-[10px] text-[#71717A] font-mono uppercase bg-[#09090B] border border-[#27272A] px-2 py-0.5 rounded">
                    {selectedFile.type} // {selectedFile.size}
                  </span>
                </div>
                <button onClick={() => setSelectedFile(null)} className="text-[#A1A1AA] hover:text-white transition-colors">
                  <X className="w-5 h-5" />
                </button>
              </div>

              {/* IDE Code Content view */}
              <div className="flex-1 bg-[#09090B] overflow-y-auto p-4 select-text">
                <div 
                  className="table w-full border-collapse"
                  dangerouslySetInnerHTML={{ __html: styleCodeLines(selectedFile.content) }}
                />
              </div>

              {/* Actions Footer */}
              <div className="bg-[#18181B] border-t border-[#27272A] p-4 flex items-center justify-between shrink-0">
                <span className="text-[10px] text-[#71717A] font-mono uppercase">{selectedFile.projectName}</span>
                
                <div className="flex items-center space-x-3">
                  <button 
                    onClick={() => handleCopy(selectedFile.content)}
                    className="inline-flex items-center space-x-2 bg-[#09090B] border border-[#27272A] text-[#A1A1AA] hover:text-white px-4 py-2 rounded-xl text-xs font-semibold transition-colors"
                  >
                    {copied ? <Check className="w-4 h-4 text-white" /> : <Copy className="w-4 h-4" />}
                    <span>{copied ? "Copied" : "Copy Code"}</span>
                  </button>
                  <button 
                    onClick={() => handleDownload(selectedFile)}
                    className="inline-flex items-center space-x-2 bg-white hover:bg-neutral-200 text-black px-4 py-2 rounded-xl text-xs font-bold transition-colors"
                  >
                    <Download className="w-4 h-4" />
                    <span>Download Asset</span>
                  </button>
                </div>
              </div>
            </motion.div>
          </div>
        )}
      </AnimatePresence>
    </div>
  );
}
